# Challenge 2

In this challenge we will continue working with the `Pokemon` dataset. We will attempt solving a slightly more complex problem in which we will practice the iterative data analysis process you leaned in [this video](https://www.youtube.com/watch?v=xOomNicqbkk).

The problem statement is as follows:

**You are at a Pokemon black market planning to buy a Pokemon for battle. All Pokemon are sold at the same price and you can only afford to buy one. You cannot choose which specific Pokemon to buy. However, you can specify the type of the Pokemon - one type that exists in either `Type 1` or `Type 2`. Which type should you choose in order to maximize your chance of receiving a good Pokemon?**

To remind you about the 3 steps of iterative data analysis, they are:

1. Setting Expectations
1. Collecting Information
1. Reacting to Data / Revising Expectations

Following the iterative process, we'll guide you in completing the challenge.


## Problem Solving Iteration 1

In this iteration we'll analyze the problem and identify the breakthrough. The original question statement is kind of vague because we don't know what a *good pokemon* really means as represented in the data. We'll start by understanding the dataset and see if we can find some insights.

In [14]:
# Import libraries
import numpy as np
import pandas as pd

In [15]:
# Importing the dataset from Ironhack's database
pokemon = pd.read_csv("../Data/Pokemon.csv")
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

From the data it seems whether a pokemon is good depends on its abilities as represented in the fields of `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total`. We are not sure about `Generation` and `Legendary` because they are not necessarily the decisive factors of the pokemon abilities.

But `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total` are a lot of fields! If we look at them all at once it's very complicated. This isn't Mission Impossible but it's ideal that we tackle this kind of problem after we learn Machine Learning (which you will do in Module 3). For now, is there a way to consolidate the fields we need to look into?

Fortunately there seems to be a way. It appears the `Total` field is computed based on the other 6 fields. But we need to prove our theory. If we can approve there is a formula to compute `Total` based on the other 6 abilities, we only need to look into `Total`.

We have the following expectation now:

#### The `Total` field is computed based on `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, and `Speed`.

We need to collect the following information:

* **What is the formula to compute `Total`?**
* **Does the formula work for all pokemon?**

In the cell below, make a hypothesis on how `Total` is computed and test your hypothesis.

In [16]:
# your code here
# Hypothesis: Total = sum[HP, Attack, Defense, Sp. Atk, Sp. Def, Speed]
pokemon["Total_check"]=pokemon["HP"]+pokemon["Attack"]+pokemon["Defense"]+pokemon["Sp. Atk"]+pokemon["Sp. Def"]+pokemon["Speed"]
pokemon.head()
# To check whether Total is equal to the calculation, we can use df method query:
pokemon.query("Total==Total_check")
len_pokemon=len(pokemon)
len_query=len(pokemon.query("Total==Total_check"))
if len_pokemon == len_query:
    print('All values in Total are the sum of HP, Attack, Defense, Sp. Atk, Sp. Def, Speed')
else:
    print('The hypothesis is incorrect')

All values in Total are the sum of HP, Attack, Defense, Sp. Atk, Sp. Def, Speed

## Problem Solving Iteration 2

Now that we have consolidated the abilities fields, we can update the problem statement. The new problem statement is:

### Which pokemon type is most likely to have the highest `Total` value?

In the updated problem statement, we assume there is a certain relationship between the `Total` and the pokemon type. But we have two *type* fields (`Type 1` and `Type 2`) that have string values. In data analysis, string fields have to be transformed to numerical format in order to be analyzed. 

In addition, keep in mind that `Type 1` always has a value but `Type 2` is sometimes empty (having the `NaN` value). Also, the pokemon type we choose may be either in `Type 1` or `Type 2`.

Now our expectation is:

#### `Type 1` and `Type 2` string variables need to be converted to numerical variables in order to identify the relationship between `Total` and the pokemon type.

The information we need to collect is:

#### How to convert two string variables to numerical?

Let's address the first question first. You can use a method called **One Hot Encoding** which is frequently used in machine learning to encode categorical string variables to numerical. The idea is to gather all the possible string values in a categorical field and create a numerical field for each unique string value. Each of those numerical fields uses `1` and `0` to indicate whether the data record has the corresponding categorical value. A detailed explanation of One Hot Encoding can be found in [this article](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f). You will formally learn it in Module 3.

For instance, if a pokemon has `Type 1` as `Poison` and `Type 2` as `Fire`, then its `Poison` and `Fire` fields are `1` whereas all other fields are `0`. If a pokemon has `Type 1` as `Water` and `Type 2` as `NaN`, then its `Water` field is `1` whereas all other fields are `0`.

#### In the next cell, use One Hot Encoding to encode `Type 1` and `Type 2`. Use the pokemon type values as the names of the numerical fields you create.

The new numerical variables you create should look like below:

![One Hot Encoding](../images/one-hot-encoding.png)

In [20]:
pd.options.display.max_columns = None
pokemon_dummies=pd.get_dummies(pokemon, columns=["Type 1", "Type 2"], prefix='', prefix_sep='', dtype=int)
pokemon_dummies

,#,Name,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total_check,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water
0,1,Bulbasaur,318,45,49,49,65,65,45,1,False,318,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,2,Ivysaur,405,60,62,63,80,80,60,1,False,405,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,3,Venusaur,525,80,82,83,100,100,80,1,False,525,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,3,VenusaurMega Venusaur,625,80,100,123,122,120,80,1,False,625,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,4,Charmander,309,39,52,43,60,50,65,1,False,309,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,600,50,100,150,100,150,50,6,True,600,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
796,719,DiancieMega Diancie,700,50,160,110,160,110,110,6,True,700,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
797,720,HoopaHoopa Confined,600,80,110,60,150,130,70,6,True,600,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
798,720,HoopaHoopa Unbound,680,80,160,60,170,130,80,6,True,680,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
799,721,Volcanion,600,80,110,120,130,90,70,6,True,600,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [23]:
#We need to remove duplicates from the columns
pokemon_dummies = pokemon_dummies.groupby(by=pokemon_dummies.columns, axis=1).sum()
pokemon_dummies = pokemon_dummies.reset_index()
pokemon_dummies.head()

C:\Users\Kristina\AppData\Local\Temp\ipykernel_636\3153937096.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  pokemon_dummies = pokemon_dummies.groupby(by=pokemon_dummies.columns, axis=1).sum()

,#,Name,Attack,Bug,Dark,Defense,Dragon,Electric,Fairy,Fighting,Fire,Flying,Generation,Ghost,Grass,Ground,HP,Ice,Legendary,Normal,Poison,Psychic,Rock,Sp. Atk,Sp. Def,Speed,Steel,Total,Total_check,Water
0,1,Bulbasaur,49,0,0,49,0,0,0,0,0,0,1,0,1,0,45,0,False,0,1,0,0,65,65,45,0,318,318,0
1,2,Ivysaur,62,0,0,63,0,0,0,0,0,0,1,0,1,0,60,0,False,0,1,0,0,80,80,60,0,405,405,0
2,3,Venusaur,82,0,0,83,0,0,0,0,0,0,1,0,1,0,80,0,False,0,1,0,0,100,100,80,0,525,525,0
3,3,VenusaurMega Venusaur,100,0,0,123,0,0,0,0,0,0,1,0,1,0,80,0,False,0,1,0,0,122,120,80,0,625,625,0
4,4,Charmander,52,0,0,43,0,0,0,0,1,0,1,0,0,0,39,0,False,0,0,0,0,60,50,65,0,309,309,0

## Problem Solving Iteration 3

Now we have encoded the pokemon types, we will identify the relationship between `Total` and the encoded fields. Our expectation is:

#### There are relationships between `Total` and the encoded pokemon type variables and we need to identify the correlations.

The information we need to collect is:

#### How to identify the relationship between `Total` and the encoded pokemon type fields?

There are multiple ways to answer this question. The easiest way is to use correlation. In the cell below, calculate the correlation of `Total` to each of the encoded fields. Rank the correlations and identify the #1 pokemon type that is most likely to have the highest `Total`.

In [34]:
# Let's do the iteration, but first let's get the list of unique Types
type1=list(pokemon["Type 1"])
type2=list(pokemon["Type 2"])

list_type=list(set(type1 + type2))
print(list_type)
list_type_clean=list_type[1:]
print(list_type_clean)

[nan, 'Electric', 'Fire', 'Dark', 'Water', 'Psychic', 'Ground', 'Flying', 'Poison', 'Bug', 'Dragon', 'Normal', 'Grass', 'Steel', 'Fighting', 'Fairy', 'Ice', 'Rock', 'Ghost']
['Electric', 'Fire', 'Dark', 'Water', 'Psychic', 'Ground', 'Flying', 'Poison', 'Bug', 'Dragon', 'Normal', 'Grass', 'Steel', 'Fighting', 'Fairy', 'Ice', 'Rock', 'Ghost']

In [41]:
# your code here
list_correlation=[]
for element in list_type_clean:
    correlation=pokemon_dummies['Total'].corr(pokemon_dummies[element])
    list_correlation.append(correlation)
    print(f'{element} correlation to Total is {correlation}')
print(max(list_correlation)) # We see that the maximum correlation is 0,2297 and it is corresponding to Dragon

Electric correlation to Total is 0.020971330428545147
Fire correlation to Total is 0.07872605613705123
Dark correlation to Total is 0.056153774076480284
Water correlation to Total is -0.021664867287180672
Psychic correlation to Total is 0.12468802510752963
Ground correlation to Total is 0.015060471925699967
Flying correlation to Total is 0.05938340252570127
Poison correlation to Total is -0.09044141387432197
Bug correlation to Total is -0.145781361252384
Dragon correlation to Total is 0.2297047163217014
Normal correlation to Total is -0.10533095102451885
Grass correlation to Total is -0.052591804857805895
Steel correlation to Total is 0.10970325430519122
Fighting correlation to Total is 0.07778621928342079
Fairy correlation to Total is -0.03669774114188013
Ice correlation to Total is 0.060248167691803606
Rock correlation to Total is 0.032731200969134455
Ghost correlation to Total is 0.0036405748393128533
0.2297047163217014

# Bonus Question

Say now you can choose both `Type 1` and `Type 2` of the pokemon. In order to receive the best pokemon, which types will you choose?

In [ ]:
# your code here